name: build_osx_M

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-14
 
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Install MacPorts
      - uses: melusina-org/setup-macports@v1

      - name: Install dependencies
        run: |
          sudo port install python311
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  
          brew update
          brew install gcc@11

      # Runs a set of commands using the runner's shell
      - name: Build-commands
        run: |
          cd $GITHUB_WORKSPACE/src
          curl -fsSL https://raw.githubusercontent.com/rcedgar/vcxproj_make/2eee480/vcxproj_make.py > vcxproj_make.py
          chmod u+x ./vcxproj_make.py
          ./vcxproj_make.py --openmp --cppcompiler g++-11 --nonative
          g++-11 --version > compiler.txt
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: muscle-osx-m
          path: |
              /Users/runner/work/muscle/muscle/bin/muscle
              /Users/runner/work/muscle/muscle/src/Makefile
              /Users/runner/work/muscle/muscle/src/make.stdout
              /Users/runner/work/muscle/muscle/src/make.stderr
              /Users/runner/work/muscle/muscle/src/compiler.txt
